apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's HTTP port.
  creationTimestamp: null
  name: http2tcp
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    deploymentConfig: datagrid-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
